---
development:
  cloud_name: eventit-me
  api_key: '789871388311843'
  api_secret: U_55LRq2EX3_9VhYiqBbeM2kTa4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: eventit-me
  api_key: '789871388311843'
  api_secret: U_55LRq2EX3_9VhYiqBbeM2kTa4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: eventit-me
  api_key: '789871388311843'
  api_secret: U_55LRq2EX3_9VhYiqBbeM2kTa4
  enhance_image_tag: true
  static_image_support: false
